---
title: "For Educators"
author:
date: 
output:
  html_document:
    fig_caption: false
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false

---
***

## Using SyncroSim in the post-secondary classroom: A collaboration with Dr. Priscilla Nyamai

The following resources can be used to support the publication “Demystifying ecological modeling: a hands-on activity to acquaint students with modeling ecosystem responses to natural and anthropogenic disturbances” *(in prep June 2024).*

This paper describes a framework for post-secondary instructors as they teach ecological modeling to college level students. The authors propose that students can enhance their ecological learning objectives, improve ecological literacy, and gain a deeper understanding of the role of ecological and anthropogenic perturbations in the environment by utilizing these hands-on creative modeling tools.


The idea of ecological modeling can be an intimidating subject to learn (and in some cases teach). For that reason, we have provided this page as a one-stop-shop for anyone interested in starting this learning process. 


 
<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/8Ybz75H9YXg?si=nzv6J2-JWGSleQmi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


<br>
<br>



### Get started here

1. [Software installation and updating guide](assets/Supplemental Material 1_ Software installation & updating guide.DOC)
2. Background literature for ecosystems
    a. [Oak Forest](assets/Supplemental material 2a_oak forest.docx)
    b. [Northern Pine-Oak Forest](assets/Supplemental material 2b_npo forest.docx)
    c. [Sugar Maple-Basswood Forest](assets/Supplemental material 2c_SMB forest.docx)
3. [Step by step modeling guide](assets/Supplemental material 3_modeling activity guide.pptx)
4. [Additional disturbances to model](assets/Supplemental material 4_ Additional disturbances.docx)
5. SyncroSim Libraries to Use
    a. [Oak Forest](assets/Supplemental material 5a_oak.ssim)
    b. [Northern Pine-Oak Forest](assets/Supplemental material 5b_npo.ssim)
    c. [Sugar Maple-Basswood Forest](assets/Supplemental material 5c_smb.ssim)
6. [Glossary of terms](assets/Supplemental material 6_Glossary of terms.docx)


<br>



### Access Free Training

[Apex RMS](https://apexrms.com/){target='blank'} is offering a [free, two-day self-directed online course](https://apexrms.com/st-sim-course-details/){target='blank'} that will provide:

>"...a foundation for developing and running state-and-transition simulation models of landscape change using the free ST-Sim software. The course covers state-and-transition simulation modeling concepts, how to use ST-Sim to create models of landscape change and terrestrial carbon dynamics, and how to run the models and interpret the results."

