---
title: "Get Models"
author: 
date:
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---
### This page:
* Get a description and model by:
    + Understanding and finding your Map Zone
    + Downloading a BpS description
    + Loading a model into SyncroSim
    
We will walk through the process with the Inter-Mountain Basins Montane Sagebrush Steppe Biophysical Setting of the Northwestern United States.  **This ecosystem will be the subject of later tutorials**. 


### Understand and find your Map Zone

First you need to know that there are hundreds of Biophysical Settings in the United States, and some of them occur in more than one Map Zone. What is a Map Zone? It's basically a product delivery and summary polygon. The polygons are from the [National Landcover Database Program](https://www.mrlc.gov/national-land-cover-database-nlcd-2016){target='blank'}.  

Pan, zoom, scroll to your area of interest, then hover over the Map Zone you need the number for. A tooltip will pop up with that info. Take note of it for the next step. 

**For our Inter-Mountain Basins Montane Sagebrush Steppe example we are looking in eastern Oregon, or Map Zone 9.**

<br>

```{r echo=FALSE, message=FALSE, warning=FALSE}
htmltools::tags$iframe(title = "My embedded document", src = "leafletSIM2carto.html", frameborder = "0", width = "100%", height="400")
```

<br>

### Download a BpS Description
Visit the [site description page](http://landfirereview.org/search.php){target='blank'}  to search for and retrieve LANDFIRE BpS model descriptions. Download the [Inter-Mountain Basins Montane Sagebrush Steppe  description](http://landfirereview.org/search.php?q=Montane%20Sage%20Steppe&hPP=20&idx=lf_landfire_dev&p=0&is_v=1){target='blank'} . This ecosystem covers Map Zone 22.
<br>


### Getting started in SyncroSim
The native environment of LANDFIRE BpS models is SyncroSim. If you want to explore or use the BpS models, you will want to familiarize yourself with and download the software:

1. Read the [overview of SyncroSim](http://docs.syncrosim.com/getting_started/overview.html){target='blank'}
2. Download and install [SyncroSim](https://syncrosim.com/){target='blank'} and the [ST-Sim](https://syncrosim.com/packages/){target='blank'} package
3. Complete the [Quickstart: An Introduction to SyncroSim](http://docs.syncrosim.com/getting_started/quickstart.html){target='blank'}


### Load your model
Once you have SyncroSim installed, and the LANDFIRE Package loaded, you will go through a few steps to isolate one model to work with. 

**You can view and print the instructions [here](./isolateModel.html){target='blank'}.**
<br>


### For more information

*  [How to Alter and Run a LANDFIRE Model in ST-Sim](https://www.youtube.com/watch?v=XUUm-RG4eK0&list=PLDFF9036BBFE46CE6&index=7&t=0s){target='blank'}

Some features of SyncroSim may be different than what you see in the video due to versioning.

***

#### What's next?
+ learn the basics of [changing disturbance probabilities across states and entire models](./modifyModel.html){target='blank'}
+ learn the basics of [adding and deleting states](./modifyModel.html){target='blank'}